title: "[域名]项目名称"
labels: ["idea", "triage"]
body:
  - type: textarea
    id: project-detail
    attributes:
      label: 项目详情
      value: |
        ```
        项目介绍
        ```
        ---
        ## 目标

        ---
        ## 计划
    validations:
      required: true
